version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_USER: ${DB_USER}  
      DB_PASSWORD: ${DB_PASSWORD}  
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}  
      POSTGRES_PASSWORD: ${DB_PASSWORD}  
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  
  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    environment:
      DB_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?sslmode=disable
    command: [ "-path", "/migrations", "-database", "$${DB_URL}", "up" ]
    depends_on:
      - db

volumes:
  db_data:
