name: Go CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.0'
          cache: 'go-modules' # Go mod cache'ini etkinleştir
      
      - name: Install dependencies
        run: |
          go mod tidy

      - name: Build
        run: go build -v -o library-system ./...
     
      - name: Test
        run: go test -v ./...