name: Go CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{secrets.DB_PORT}}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.0'
      
      - name: Install Docker Compose
        run: |
          sudo curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Build and Run using Makefile
        run: |
          make run DB_USER=${{ secrets.DB_USER }} DB_PASSWORD=${{ secrets.DB_PASSWORD }} DB_NAME=${{ secrets.DB_NAME }} DB_PORT=${{ secrets.DB_PORT }}

      - name: Wait for PostgreSQL to be ready
        run: |
          DB_CONTAINER_ID=$(docker ps -qf "name=db")  # Get the container ID of the PostgreSQL service
          until docker exec $DB_CONTAINER_ID pg_isready -U ${DB_USER} -d ${DB_NAME}; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done
          echo "PostgreSQL is ready!"

      - name: View logs from all Docker containers
        run: |
          container_ids=$(docker ps -q)  # Get all container IDs
          echo "Container IDs: $container_ids"
          for id in $container_ids; do
            echo "Logs for container $id:"
            docker logs $id  # Show logs for each container
          done

      - name: Check if the app is running
        run: |
          for i in {1..10}; do
            if curl --fail http://localhost:8080; then
              echo "App is running!"
              exit 0
            else
              echo "App is not ready yet. Retrying in 5 seconds..."
              sleep 5
            fi
          done
          echo "App failed to start within the expected time."
          exit 1

      - name: Docker Compose down
        run: |
          make run clean